### ISSUE TITLE
Frequent Crash

### ISSUE THREAD

**Issue by manikandancode** [Bavarder/Bavarder#19]
OS: Ubuntu 23.04 Wayland

https://user-images.githubusercontent.com/46480489/236608750-3370d7f8-e63d-4331-be64-24324b65775b.mp4

![image](https://user-images.githubusercontent.com/46480489/236608784-18e7c7c7-1948-49e5-bdba-6366b0a0c474.png)

**Comment by vroger11** [comment]
Got same problem under kde:

Full trace:
```
flatpak run io.github.Bavarder.Bavarder

(bavarder:2): Gtk-WARNING **: 09:56:33.909: Unknown key gtk-modules in /home/vroger/.var/app/io.github.Bavarder.Bavarder/config/gtk-4.0/settings.ini
@a{ss} {}
['baichat', 'catgpt', 'huggingchat', 'openaigpt35turbo', 'openaigpt4']
Loading provider baichat
Provider baichat  -> KeyError, skipping...
Loading provider catgpt
Provider catgpt  -> KeyError, skipping...
Loading provider huggingchat
Provider huggingchat  -> KeyError, skipping...
Loading provider openaigpt35turbo
Provider openaigpt35turbo  -> KeyError, skipping...
Loading provider openaigpt4
Provider openaigpt4  -> KeyError, skipping...
huggingchat
Setting selected provider to 2
**
Gtk:ERROR:../gtk/gtktextview.c:4764:gtk_text_view_validate_onscreen: assertion failed: (priv->onscreen_validated)
Bail out! Gtk:ERROR:../gtk/gtktextview.c:4764:gtk_text_view_validate_onscreen: assertion failed: (priv->onscreen_validated)
```

**Comment by 0xMRTT** [comment]
Fixed in https://codeberg.org/Bavarder/Bavarder/commit/6cf10e6f2e975ae34ef28c00ff84f8901199f624

**Comment by 0xMRTT** [comment]
Fixed in 0.1.6

**Comment by CaptainMorgan12** [comment]
Can this be re-opened. Crashes still occur on mobile phone L5 with OSK squeekboard and flatpak bavarder app 0.1.6 on wayland gtk.

Steps to repeat:

1. unfold osk 
2. select text entry field using touch
3. fold osk
4. unfold osk
5. Repeat steps quickly while occasionally selecting different areas of entry field

Observe it sometimes crashes the app. This appears to happen particularly if app was opened first time.

**Comment by 0xMRTT** [comment]
0.1.7 has been released :rocket:
